// Initial catalog used to seed an empty database on first run.
// Kept in the same shape the storefront expects (see js/products.js).
export const SEED_PRODUCTS = [
  { id: 'p01', name: 'Velocity Pro Tee',   cat: 'Koszulki',  brand: 'Nike',        condition: 'Nowy',    price: 89,  old: 149, tag: '-40%',   tagType: 'sale', stars: 5, sizes: ['S','M','L','XL'], colors: ['Czarny','Czerwony'], gradient: 'linear-gradient(135deg,#2a0409,#1c1c22)' },
  { id: 'p02', name: 'Apex Track Jacket',  cat: 'Bluzy',     brand: 'Adidas',      condition: 'Nowy',    price: 259, old: 399, tag: 'HIT',    tagType: 'hit',  stars: 5, sizes: ['M','L','XL','XXL'], colors: ['Czarny','Szary'], gradient: 'linear-gradient(135deg,#1c1c22,#320810)' },
  { id: 'p03', name: 'Redline Joggers',    cat: 'Spodnie',   brand: 'Puma',        condition: 'Używany', price: 179, old: 249, tag: '-28%',   tagType: 'sale', stars: 4, sizes: ['S','M','L'], colors: ['Szary','Czarny'], gradient: 'linear-gradient(135deg,#151519,#2a0409)' },
  { id: 'p04', name: 'Surge Windbreaker',  cat: 'Kurtki',    brand: 'Nike',        condition: 'Nowy',    price: 329, old: 449, tag: 'NOWOŚĆ', tagType: 'new',  stars: 5, sizes: ['M','L','XL'], colors: ['Czarny','Czerwony'], gradient: 'linear-gradient(135deg,#2a0409,#0f0f12)' },
  { id: 'p05', name: 'Boost Runner GT',    cat: 'Obuwie',    brand: 'Adidas',      condition: 'Nowy',    price: 419, old: 599, tag: '-30%',   tagType: 'sale', stars: 5, sizes: ['M','L','XL','XXL'], colors: ['Czarny','Biały'], gradient: 'linear-gradient(135deg,#1c1c22,#2a0409)' },
  { id: 'p06', name: 'Torque Cap',         cat: 'Akcesoria', brand: 'New Balance', condition: 'Nowy',    price: 69,  old: 99,  tag: 'HIT',    tagType: 'hit',  stars: 4, sizes: ['M','L'], colors: ['Czarny','Czerwony'], gradient: 'linear-gradient(135deg,#320810,#151519)' },
  { id: 'p07', name: 'Nitro Compression',  cat: 'Koszulki',  brand: 'Under Armour',condition: 'Nowy',    price: 119, old: 169, tag: '-29%',   tagType: 'sale', stars: 5, sizes: ['XS','S','M','L'], colors: ['Czerwony','Czarny'], gradient: 'linear-gradient(135deg,#0f0f12,#2a0409)' },
  { id: 'p08', name: 'Drift Cargo Pants',  cat: 'Spodnie',   brand: 'Puma',        condition: 'Używany', price: 219, old: 299, tag: 'NOWOŚĆ', tagType: 'new',  stars: 4, sizes: ['S','M','L','XL'], colors: ['Szary','Czarny'], gradient: 'linear-gradient(135deg,#2a0409,#1c1c22)' },
  { id: 'p09', name: 'Ignite Hoodie',      cat: 'Bluzy',     brand: 'Nike',        condition: 'Nowy',    price: 199, old: 279, tag: '-28%',   tagType: 'sale', stars: 5, sizes: ['M','L','XL','XXL'], colors: ['Czarny','Czerwony'], gradient: 'linear-gradient(135deg,#1c1c22,#320810)' },
  { id: 'p10', name: 'Sprint Shorts 2.0',  cat: 'Spodnie',   brand: 'Reebok',      condition: 'Używany', price: 99,  old: 139, tag: 'HIT',    tagType: 'hit',  stars: 4, sizes: ['XS','S','M','L'], colors: ['Czarny','Biały'], gradient: 'linear-gradient(135deg,#151519,#2a0409)' },
  { id: 'p11', name: 'Carbon Duffel Bag',  cat: 'Akcesoria', brand: 'Adidas',      condition: 'Nowy',    price: 289, old: 399, tag: '-27%',   tagType: 'sale', stars: 5, sizes: ['M','L'], colors: ['Czarny','Szary'], gradient: 'linear-gradient(135deg,#2a0409,#0f0f12)' },
  { id: 'p12', name: 'Phantom Trail Shoe', cat: 'Obuwie',    brand: 'New Balance', condition: 'Używany', price: 379, old: 529, tag: 'NOWOŚĆ', tagType: 'new',  stars: 5, sizes: ['M','L','XL'], colors: ['Czarny','Biały'], gradient: 'linear-gradient(135deg,#1c1c22,#2a0409)' },
];
