// Initial catalog used to seed an empty database on first run.
// Kept in the same shape the storefront expects (see js/products.js).
export const SEED_PRODUCTS = [
  { id: 'p01', name: 'Predator Elite FG',       cat: 'Buty piłkarskie',      brand: 'Adidas',      condition: 'Nowy', level: 'Profesjonalne',     surface: 'Na trawę (lanki)',                 price: 649, old: 899, tag: '-28%',   tagType: 'sale', stars: 5, sizes: ['40','41','42','43','44'], colors: [], gradient: 'linear-gradient(135deg,#2a0409,#1c1c22)' },
  { id: 'p02', name: 'Phantom GX Pro FG',       cat: 'Buty piłkarskie',      brand: 'Nike',        condition: 'Nowy', level: 'Półprofesjonalne',  surface: 'Na trawę (lanki)',                 price: 459, old: 649, tag: 'HIT',    tagType: 'hit',  stars: 5, sizes: ['40','41','42','43','44','45'], colors: [], gradient: 'linear-gradient(135deg,#1c1c22,#320810)' },
  { id: 'p03', name: 'Future Match TF',         cat: 'Buty piłkarskie',      brand: 'Puma',        condition: 'Nowy', level: 'Treningowe',        surface: 'Na sztuczną trawę/orlika (turfy)', price: 259, old: 359, tag: '-28%',   tagType: 'sale', stars: 4, sizes: ['40','41','42','43','44'], colors: [], gradient: 'linear-gradient(135deg,#151519,#2a0409)' },
  { id: 'p04', name: 'Mercurial Vapor SG',      cat: 'Buty piłkarskie',      brand: 'Nike',        condition: 'Nowy', level: 'Profesjonalne',     surface: 'Na mokrą trawę (wkręty/mixy)',     price: 589, old: 799, tag: 'NOWOŚĆ', tagType: 'new',  stars: 5, sizes: ['41','42','43','44','45'], colors: [], gradient: 'linear-gradient(135deg,#2a0409,#0f0f12)' },
  { id: 'p05', name: 'Copa Sala IN',            cat: 'Buty piłkarskie',      brand: 'Adidas',      condition: 'Nowy', level: 'Rekreacyjne',       surface: 'Na halę (halówki)',                price: 199, old: 279, tag: '-29%',   tagType: 'sale', stars: 4, sizes: ['39','40','41','42','43','44'], colors: [], gradient: 'linear-gradient(135deg,#1c1c22,#2a0409)' },
  { id: 'p06', name: 'Tiempo Legend TF',        cat: 'Buty piłkarskie',      brand: 'Nike',        condition: 'Nowy', level: 'Treningowe',        surface: 'Na sztuczną trawę/orlika (turfy)', price: 339, old: 469, tag: 'HIT',    tagType: 'hit',  stars: 5, sizes: ['40','41','42','43','44'], colors: [], gradient: 'linear-gradient(135deg,#320810,#151519)' },
  { id: 'p07', name: 'Predator GK Pro',         cat: 'Rękawice bramkarskie', brand: 'Adidas',      condition: 'Nowy', level: '',                  surface: '',                                 price: 219, old: 299, tag: '-27%',   tagType: 'sale', stars: 5, sizes: ['8','9','10','11'], colors: [], gradient: 'linear-gradient(135deg,#0f0f12,#2a0409)' },
  { id: 'p08', name: 'GK Vapor Grip3',          cat: 'Rękawice bramkarskie', brand: 'Nike',        condition: 'Nowy', level: '',                  surface: '',                                 price: 279, old: 379, tag: 'NOWOŚĆ', tagType: 'new',  stars: 4, sizes: ['8','9','10','11'], colors: [], gradient: 'linear-gradient(135deg,#2a0409,#1c1c22)' },
  { id: 'p09', name: 'Piłka meczowa Pro',       cat: 'Piłki',                brand: 'Adidas',      condition: 'Nowy', level: '',                  surface: '',                                 price: 159, old: 219, tag: '-27%',   tagType: 'sale', stars: 5, sizes: ['4','5'], colors: [], gradient: 'linear-gradient(135deg,#1c1c22,#320810)' },
  { id: 'p10', name: 'Piłka treningowa Club',   cat: 'Piłki',                brand: 'Nike',        condition: 'Nowy', level: '',                  surface: '',                                 price: 89,  old: 129, tag: 'HIT',    tagType: 'hit',  stars: 4, sizes: ['4','5'], colors: [], gradient: 'linear-gradient(135deg,#151519,#2a0409)' },
  { id: 'p11', name: 'Buty sportowe RunFlex',   cat: 'Buty sportowe',        brand: 'New Balance', condition: 'Nowy', level: '',                  surface: '',                                 price: 289, old: 399, tag: '-27%',   tagType: 'sale', stars: 5, sizes: ['40','41','42','43','44'], colors: [], gradient: 'linear-gradient(135deg,#2a0409,#0f0f12)' },
  { id: 'p12', name: 'Ochraniacze Guard Pro',   cat: 'Akcesoria',            brand: 'Puma',        condition: 'Nowy', level: '',                  surface: '',                                 price: 59,  old: 89,  tag: 'NOWOŚĆ', tagType: 'new',  stars: 5, sizes: ['S','M','L'], colors: [], gradient: 'linear-gradient(135deg,#1c1c22,#2a0409)' },
];
